# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /sbin/cmake

# The command to remove a file.
RM = /sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nsomnia/Documents/zzzz_VISUALIZER-WORKING-COPY

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nsomnia/Documents/zzzz_VISUALIZER-WORKING-COPY

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nsomnia/Documents/zzzz_VISUALIZER-WORKING-COPY/CMakeFiles /home/nsomnia/Documents/zzzz_VISUALIZER-WORKING-COPY//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nsomnia/Documents/zzzz_VISUALIZER-WORKING-COPY/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projectM_external

# Build rule for target.
projectM_external: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projectM_external
.PHONY : projectM_external

# fast build rule for target.
projectM_external/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projectM_external.dir/build.make CMakeFiles/projectM_external.dir/build
.PHONY : projectM_external/fast

#=============================================================================
# Target rules for targets named AuroraVisualizer

# Build rule for target.
AuroraVisualizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraVisualizer
.PHONY : AuroraVisualizer

# fast build rule for target.
AuroraVisualizer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/build
.PHONY : AuroraVisualizer/fast

#=============================================================================
# Target rules for targets named create_source_backup

# Build rule for target.
create_source_backup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 create_source_backup
.PHONY : create_source_backup

# fast build rule for target.
create_source_backup/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/create_source_backup.dir/build.make CMakeFiles/create_source_backup.dir/build
.PHONY : create_source_backup/fast

#=============================================================================
# Target rules for targets named AuroraVisualizer_autogen_timestamp_deps

# Build rule for target.
AuroraVisualizer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraVisualizer_autogen_timestamp_deps
.PHONY : AuroraVisualizer_autogen_timestamp_deps

# fast build rule for target.
AuroraVisualizer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer_autogen_timestamp_deps.dir/build.make CMakeFiles/AuroraVisualizer_autogen_timestamp_deps.dir/build
.PHONY : AuroraVisualizer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named AuroraVisualizer_autogen

# Build rule for target.
AuroraVisualizer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraVisualizer_autogen
.PHONY : AuroraVisualizer_autogen

# fast build rule for target.
AuroraVisualizer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer_autogen.dir/build.make CMakeFiles/AuroraVisualizer_autogen.dir/build
.PHONY : AuroraVisualizer_autogen/fast

AuroraVisualizer_autogen/mocs_compilation.o: AuroraVisualizer_autogen/mocs_compilation.cpp.o
.PHONY : AuroraVisualizer_autogen/mocs_compilation.o

# target to build an object file
AuroraVisualizer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/AuroraVisualizer_autogen/mocs_compilation.cpp.o
.PHONY : AuroraVisualizer_autogen/mocs_compilation.cpp.o

AuroraVisualizer_autogen/mocs_compilation.i: AuroraVisualizer_autogen/mocs_compilation.cpp.i
.PHONY : AuroraVisualizer_autogen/mocs_compilation.i

# target to preprocess a source file
AuroraVisualizer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/AuroraVisualizer_autogen/mocs_compilation.cpp.i
.PHONY : AuroraVisualizer_autogen/mocs_compilation.cpp.i

AuroraVisualizer_autogen/mocs_compilation.s: AuroraVisualizer_autogen/mocs_compilation.cpp.s
.PHONY : AuroraVisualizer_autogen/mocs_compilation.s

# target to generate assembly for a file
AuroraVisualizer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/AuroraVisualizer_autogen/mocs_compilation.cpp.s
.PHONY : AuroraVisualizer_autogen/mocs_compilation.cpp.s

include/moc_QtGui.o: include/moc_QtGui.cpp.o
.PHONY : include/moc_QtGui.o

# target to build an object file
include/moc_QtGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/include/moc_QtGui.cpp.o
.PHONY : include/moc_QtGui.cpp.o

include/moc_QtGui.i: include/moc_QtGui.cpp.i
.PHONY : include/moc_QtGui.i

# target to preprocess a source file
include/moc_QtGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/include/moc_QtGui.cpp.i
.PHONY : include/moc_QtGui.cpp.i

include/moc_QtGui.s: include/moc_QtGui.cpp.s
.PHONY : include/moc_QtGui.s

# target to generate assembly for a file
include/moc_QtGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/include/moc_QtGui.cpp.s
.PHONY : include/moc_QtGui.cpp.s

include/moc_QtOpenGLWidget.o: include/moc_QtOpenGLWidget.cpp.o
.PHONY : include/moc_QtOpenGLWidget.o

# target to build an object file
include/moc_QtOpenGLWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/include/moc_QtOpenGLWidget.cpp.o
.PHONY : include/moc_QtOpenGLWidget.cpp.o

include/moc_QtOpenGLWidget.i: include/moc_QtOpenGLWidget.cpp.i
.PHONY : include/moc_QtOpenGLWidget.i

# target to preprocess a source file
include/moc_QtOpenGLWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/include/moc_QtOpenGLWidget.cpp.i
.PHONY : include/moc_QtOpenGLWidget.cpp.i

include/moc_QtOpenGLWidget.s: include/moc_QtOpenGLWidget.cpp.s
.PHONY : include/moc_QtOpenGLWidget.s

# target to generate assembly for a file
include/moc_QtOpenGLWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/include/moc_QtOpenGLWidget.cpp.s
.PHONY : include/moc_QtOpenGLWidget.cpp.s

src/AnimationManager.o: src/AnimationManager.cpp.o
.PHONY : src/AnimationManager.o

# target to build an object file
src/AnimationManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/AnimationManager.cpp.o
.PHONY : src/AnimationManager.cpp.o

src/AnimationManager.i: src/AnimationManager.cpp.i
.PHONY : src/AnimationManager.i

# target to preprocess a source file
src/AnimationManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/AnimationManager.cpp.i
.PHONY : src/AnimationManager.cpp.i

src/AnimationManager.s: src/AnimationManager.cpp.s
.PHONY : src/AnimationManager.s

# target to generate assembly for a file
src/AnimationManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/AnimationManager.cpp.s
.PHONY : src/AnimationManager.cpp.s

src/CliParser.o: src/CliParser.cpp.o
.PHONY : src/CliParser.o

# target to build an object file
src/CliParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/CliParser.cpp.o
.PHONY : src/CliParser.cpp.o

src/CliParser.i: src/CliParser.cpp.i
.PHONY : src/CliParser.i

# target to preprocess a source file
src/CliParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/CliParser.cpp.i
.PHONY : src/CliParser.cpp.i

src/CliParser.s: src/CliParser.cpp.s
.PHONY : src/CliParser.s

# target to generate assembly for a file
src/CliParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/CliParser.cpp.s
.PHONY : src/CliParser.cpp.s

src/ConfigLoader.o: src/ConfigLoader.cpp.o
.PHONY : src/ConfigLoader.o

# target to build an object file
src/ConfigLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/ConfigLoader.cpp.o
.PHONY : src/ConfigLoader.cpp.o

src/ConfigLoader.i: src/ConfigLoader.cpp.i
.PHONY : src/ConfigLoader.i

# target to preprocess a source file
src/ConfigLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/ConfigLoader.cpp.i
.PHONY : src/ConfigLoader.cpp.i

src/ConfigLoader.s: src/ConfigLoader.cpp.s
.PHONY : src/ConfigLoader.s

# target to generate assembly for a file
src/ConfigLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/ConfigLoader.cpp.s
.PHONY : src/ConfigLoader.cpp.s

src/QtGui.o: src/QtGui.cpp.o
.PHONY : src/QtGui.o

# target to build an object file
src/QtGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/QtGui.cpp.o
.PHONY : src/QtGui.cpp.o

src/QtGui.i: src/QtGui.cpp.i
.PHONY : src/QtGui.i

# target to preprocess a source file
src/QtGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/QtGui.cpp.i
.PHONY : src/QtGui.cpp.i

src/QtGui.s: src/QtGui.cpp.s
.PHONY : src/QtGui.s

# target to generate assembly for a file
src/QtGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/QtGui.cpp.s
.PHONY : src/QtGui.cpp.s

src/QtOpenGLWidget.o: src/QtOpenGLWidget.cpp.o
.PHONY : src/QtOpenGLWidget.o

# target to build an object file
src/QtOpenGLWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/QtOpenGLWidget.cpp.o
.PHONY : src/QtOpenGLWidget.cpp.o

src/QtOpenGLWidget.i: src/QtOpenGLWidget.cpp.i
.PHONY : src/QtOpenGLWidget.i

# target to preprocess a source file
src/QtOpenGLWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/QtOpenGLWidget.cpp.i
.PHONY : src/QtOpenGLWidget.cpp.i

src/QtOpenGLWidget.s: src/QtOpenGLWidget.cpp.s
.PHONY : src/QtOpenGLWidget.s

# target to generate assembly for a file
src/QtOpenGLWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/QtOpenGLWidget.cpp.s
.PHONY : src/QtOpenGLWidget.cpp.s

src/TextManager.o: src/TextManager.cpp.o
.PHONY : src/TextManager.o

# target to build an object file
src/TextManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/TextManager.cpp.o
.PHONY : src/TextManager.cpp.o

src/TextManager.i: src/TextManager.cpp.i
.PHONY : src/TextManager.i

# target to preprocess a source file
src/TextManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/TextManager.cpp.i
.PHONY : src/TextManager.cpp.i

src/TextManager.s: src/TextManager.cpp.s
.PHONY : src/TextManager.s

# target to generate assembly for a file
src/TextManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/TextManager.cpp.s
.PHONY : src/TextManager.cpp.s

src/TextRenderer.o: src/TextRenderer.cpp.o
.PHONY : src/TextRenderer.o

# target to build an object file
src/TextRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/TextRenderer.cpp.o
.PHONY : src/TextRenderer.cpp.o

src/TextRenderer.i: src/TextRenderer.cpp.i
.PHONY : src/TextRenderer.i

# target to preprocess a source file
src/TextRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/TextRenderer.cpp.i
.PHONY : src/TextRenderer.cpp.i

src/TextRenderer.s: src/TextRenderer.cpp.s
.PHONY : src/TextRenderer.s

# target to generate assembly for a file
src/TextRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/TextRenderer.cpp.s
.PHONY : src/TextRenderer.cpp.s

src/VideoExporter.o: src/VideoExporter.cpp.o
.PHONY : src/VideoExporter.o

# target to build an object file
src/VideoExporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/VideoExporter.cpp.o
.PHONY : src/VideoExporter.cpp.o

src/VideoExporter.i: src/VideoExporter.cpp.i
.PHONY : src/VideoExporter.i

# target to preprocess a source file
src/VideoExporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/VideoExporter.cpp.i
.PHONY : src/VideoExporter.cpp.i

src/VideoExporter.s: src/VideoExporter.cpp.s
.PHONY : src/VideoExporter.s

# target to generate assembly for a file
src/VideoExporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/VideoExporter.cpp.s
.PHONY : src/VideoExporter.cpp.s

src/backends/audio_backend.o: src/backends/audio_backend.cpp.o
.PHONY : src/backends/audio_backend.o

# target to build an object file
src/backends/audio_backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/backends/audio_backend.cpp.o
.PHONY : src/backends/audio_backend.cpp.o

src/backends/audio_backend.i: src/backends/audio_backend.cpp.i
.PHONY : src/backends/audio_backend.i

# target to preprocess a source file
src/backends/audio_backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/backends/audio_backend.cpp.i
.PHONY : src/backends/audio_backend.cpp.i

src/backends/audio_backend.s: src/backends/audio_backend.cpp.s
.PHONY : src/backends/audio_backend.s

# target to generate assembly for a file
src/backends/audio_backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/backends/audio_backend.cpp.s
.PHONY : src/backends/audio_backend.cpp.s

src/backends/display_backend.o: src/backends/display_backend.cpp.o
.PHONY : src/backends/display_backend.o

# target to build an object file
src/backends/display_backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/backends/display_backend.cpp.o
.PHONY : src/backends/display_backend.cpp.o

src/backends/display_backend.i: src/backends/display_backend.cpp.i
.PHONY : src/backends/display_backend.i

# target to preprocess a source file
src/backends/display_backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/backends/display_backend.cpp.i
.PHONY : src/backends/display_backend.cpp.i

src/backends/display_backend.s: src/backends/display_backend.cpp.s
.PHONY : src/backends/display_backend.s

# target to generate assembly for a file
src/backends/display_backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/backends/display_backend.cpp.s
.PHONY : src/backends/display_backend.cpp.s

src/core.o: src/core.cpp.o
.PHONY : src/core.o

# target to build an object file
src/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core.cpp.o
.PHONY : src/core.cpp.o

src/core.i: src/core.cpp.i
.PHONY : src/core.i

# target to preprocess a source file
src/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core.cpp.i
.PHONY : src/core.cpp.i

src/core.s: src/core.cpp.s
.PHONY : src/core.s

# target to generate assembly for a file
src/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core.cpp.s
.PHONY : src/core.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/preset_manager.o: src/preset_manager.cpp.o
.PHONY : src/preset_manager.o

# target to build an object file
src/preset_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/preset_manager.cpp.o
.PHONY : src/preset_manager.cpp.o

src/preset_manager.i: src/preset_manager.cpp.i
.PHONY : src/preset_manager.i

# target to preprocess a source file
src/preset_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/preset_manager.cpp.i
.PHONY : src/preset_manager.cpp.i

src/preset_manager.s: src/preset_manager.cpp.s
.PHONY : src/preset_manager.s

# target to generate assembly for a file
src/preset_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/preset_manager.cpp.s
.PHONY : src/preset_manager.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/utils/Logger.o: src/utils/Logger.cpp.o
.PHONY : src/utils/Logger.o

# target to build an object file
src/utils/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/utils/Logger.cpp.o
.PHONY : src/utils/Logger.cpp.o

src/utils/Logger.i: src/utils/Logger.cpp.i
.PHONY : src/utils/Logger.i

# target to preprocess a source file
src/utils/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/utils/Logger.cpp.i
.PHONY : src/utils/Logger.cpp.i

src/utils/Logger.s: src/utils/Logger.cpp.s
.PHONY : src/utils/Logger.s

# target to generate assembly for a file
src/utils/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/utils/Logger.cpp.s
.PHONY : src/utils/Logger.cpp.s

src/utils/common.o: src/utils/common.cpp.o
.PHONY : src/utils/common.o

# target to build an object file
src/utils/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/utils/common.cpp.o
.PHONY : src/utils/common.cpp.o

src/utils/common.i: src/utils/common.cpp.i
.PHONY : src/utils/common.i

# target to preprocess a source file
src/utils/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/utils/common.cpp.i
.PHONY : src/utils/common.cpp.i

src/utils/common.s: src/utils/common.cpp.s
.PHONY : src/utils/common.s

# target to generate assembly for a file
src/utils/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/utils/common.cpp.s
.PHONY : src/utils/common.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AuroraVisualizer_autogen"
	@echo "... AuroraVisualizer_autogen_timestamp_deps"
	@echo "... create_source_backup"
	@echo "... projectM_external"
	@echo "... AuroraVisualizer"
	@echo "... AuroraVisualizer_autogen/mocs_compilation.o"
	@echo "... AuroraVisualizer_autogen/mocs_compilation.i"
	@echo "... AuroraVisualizer_autogen/mocs_compilation.s"
	@echo "... include/moc_QtGui.o"
	@echo "... include/moc_QtGui.i"
	@echo "... include/moc_QtGui.s"
	@echo "... include/moc_QtOpenGLWidget.o"
	@echo "... include/moc_QtOpenGLWidget.i"
	@echo "... include/moc_QtOpenGLWidget.s"
	@echo "... src/AnimationManager.o"
	@echo "... src/AnimationManager.i"
	@echo "... src/AnimationManager.s"
	@echo "... src/CliParser.o"
	@echo "... src/CliParser.i"
	@echo "... src/CliParser.s"
	@echo "... src/ConfigLoader.o"
	@echo "... src/ConfigLoader.i"
	@echo "... src/ConfigLoader.s"
	@echo "... src/QtGui.o"
	@echo "... src/QtGui.i"
	@echo "... src/QtGui.s"
	@echo "... src/QtOpenGLWidget.o"
	@echo "... src/QtOpenGLWidget.i"
	@echo "... src/QtOpenGLWidget.s"
	@echo "... src/TextManager.o"
	@echo "... src/TextManager.i"
	@echo "... src/TextManager.s"
	@echo "... src/TextRenderer.o"
	@echo "... src/TextRenderer.i"
	@echo "... src/TextRenderer.s"
	@echo "... src/VideoExporter.o"
	@echo "... src/VideoExporter.i"
	@echo "... src/VideoExporter.s"
	@echo "... src/backends/audio_backend.o"
	@echo "... src/backends/audio_backend.i"
	@echo "... src/backends/audio_backend.s"
	@echo "... src/backends/display_backend.o"
	@echo "... src/backends/display_backend.i"
	@echo "... src/backends/display_backend.s"
	@echo "... src/core.o"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/preset_manager.o"
	@echo "... src/preset_manager.i"
	@echo "... src/preset_manager.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/utils/Logger.o"
	@echo "... src/utils/Logger.i"
	@echo "... src/utils/Logger.s"
	@echo "... src/utils/common.o"
	@echo "... src/utils/common.i"
	@echo "... src/utils/common.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

